"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../components/ChatActionBar/style/css");
require("../components/ChatSettingDrawer/style/css");
require("../components/ChatHeader/style/css");
require("../components/ChatP2pMessageList/style/css");
require("../components/ChatMessageItem/style/css");
require("../components/ChatMessageInput/style/css");
require("../components/ChatAddMembers/style/css");
require("../components/ChatCreateTeam/style/css");
require("../components/ChatP2pSetting/style/css");
require("../components/ChatTeamSetting/style/css");
require("../components/ChatForwardModal/style/css");
require("../components/ChatTeamMemberModal/style/css");
require("../components/ChatGroupTransferModal/style/css");
require("../../common/components/FriendSelect/style/css");
require("../../common/components/GroupAvatarSelect/style/css");
require("../../common/components/CrudeAvatar/style/css");
require("../../common/components/ComplexAvatar/style/css");
require("../../common/components/CommonParseSession/style/css");
require("../../common/components/Welcome/style/css");
require("./index.css");
