"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("antd/lib/spin/style");
require("antd/lib/empty/style");
require("antd/lib/button/style");
require("antd/lib/message/style");
require("../../../common/components/ComplexAvatar/style");
require("../../../common/components/CrudeAvatar/style");
require("./msgList.less");
require("./msgItem.less");
