"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./groupList.less");
require("./groupItem.less");
require("./groupDetail.less");
require("./groupPower.less");
require("./index.less");
require("antd/lib/form/style");
require("antd/lib/input/style");
require("antd/lib/button/style");
require("antd/lib/select/style");
require("antd/lib/modal/style");
require("antd/lib/switch/style");
require("antd/lib/radio/style");
require("antd/lib/message/style");
require("antd/lib/empty/style");
